version: '3'

services:
  proxy:
    build: ./proxy/
    ports:
      - "5000:5000"
    networks:
      - users
      - meteo

  back-users:
    build: ./api-users/
    networks:
      - users

  back-meteo:
    build: ./api-meteo/
    networks:
      - meteo

networks:
  users:
  meteo:
